services:
  - type: web
    name: kindergarten-backend
    env: node
    repo: https://github.com/houari777/kindergarten-frontend.git
    region: frankfurt
    plan: free
    branch: main
    rootDir: backend
    buildFilter:
      paths:
      - backend/**
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: JWT_SECRET
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FCM_SERVER_KEY
        sync: false

  - type: web
    name: kindergarten-dashboard
    env: static
    repo: https://github.com/houari777/kindergarten-frontend.git
    region: frankfurt
    plan: free
    branch: main
    rootDir: dashboard
    buildFilter:
      paths:
      - dashboard/**
    buildCommand: "npm install && npm run build"
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html